Add listing of organization members
auth0/auth0-cli pull request #378
Opened 2021-12-30 23:27 UTC by sergeybykov

By submitting a PR to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/auth0/.github/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.

### Description

Added `members` subcommand (`membersOrganizationCmd` func) to the `orgs` command to list members of an organiozation.
Added a `Members` method to `OrganizationAPI` interface to expose the underlying API.
Added `membersView` for rendering a list of members.
Refactored the pagination logic into a `getWithPagination` helper func to reuse the logic between `membersOrganizationCmd` and `listAppsCmd`. This required some ugly manipulation of slices due to the lack of generics. Maybe there's a better way to do this?

Fixes #377 

### References

Fixes #377.

### Testing

> Describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.
>
> Please include any manual steps for testing end-to-end or functionality not covered by unit/integration tests.
>
> Also include details of the environment this PR was developed in (language/platform/browser version).

I tested this by executing the new cli subcommand against existing orgs.
I'm happy to add unit/integrations tests if somebody could guide me how this is done here.

- [ ] This change adds test coverage for new/changed/fixed functionality

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [x] All active GitHub checks for tests, formatting, and security are passing
- [x] The correct base branch is being used, if not `master`

2022-01-04 02:23 UTC, Widcket commented
Hi @sergeybykov, thanks for raising this. I haven't been able to take a look at the PR yet. When I have some bandwidth I'll circle back and review.

2022-01-04 02:24 UTC, Widcket commented
Hi @sergeybykov, thanks for raising this. Is this PR ready for review?

2022-01-04 02:29 UTC, sergeybykov commented
Hi @Widcket, yes it is ready. I only made it a draft because wanted to hear on the issue first.

2022-01-04 03:01 UTC, Widcket commented
I'm busy right now, but I'll circle back when I have some bandwidth.

2022-01-15 04:06 UTC, sergeybykov commented
Hi @Widcket, did you get a chance to take a look?

2022-01-18 00:26 UTC, Widcket commented on internal/cli/organizations.go
> +auth0 orgs members <id>`,
This command should be `auth0 orgs member list <id>`. See https://auth0.github.io/auth0-cli/auth0_apis_scopes_list.html for a similar example (`auth0 apis scopes list <id>`).

2022-01-18 00:37 UTC, Widcket commented on internal/display/members.go
> +		{"NAME", v.Name},
```suggestion
		{"Name", v.Name},
```

2022-01-18 00:39 UTC, Widcket commented on internal/display/members.go
> +		{"Email", v.Email},
The keys for the key/value view should be in all caps. See https://github.com/auth0/auth0-cli/blob/main/internal/display/organizations.go#L33 as an example.

2022-01-18 00:45 UTC, Widcket requested changes
Thanks for this PR! Please have the command be `auth0 orgs members list <id>` and address the formatting issue in the ke/value list.

2022-01-18 01:27 UTC, sergeybykov commented
Thanks for reviewing, @Widcket.
I believe I addressed your feedback.

2022-01-18 12:48 UTC, merged

2022-01-19 23:08 UTC, Widcket commented
This is now out in [v0.11.4](https://github.com/auth0/auth0-cli/releases/tag/v0.11.4).