Add commands for listing roles and members assigned a role in an organization
auth0/auth0-cli pull request #386
Opened 2022-01-20 03:15 UTC by sergeybykov

### Description

This adds two commands.

`auth0 orgs roles list <org ID>` for listing roles that are assigned to members of an organization.
and
`auth0 orgs roles members <org ID> <role ID>` for listing members of an organization that have a given role assigned.

The current implementation is not efficient because it has to enumerate all members and make a call for each member to retrieve their roles. There is an [outstanding ask](https://community.auth0.com/t/find-members-from-organization-with-specific-role/65626/10?u=sbykov) to Auth0 to add APIs for getting roles and members with a role assigned with single API calls instead of enumerating members.

### References

#379
[Forum thread](https://community.auth0.com/t/find-members-from-organization-with-specific-role/65626/10?u=sbykov) 

### Testing

Manual testing against a tenant with an organization populated with members that have roles assigned to them.

- [ ] This change adds test coverage for new/changed/fixed functionality

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [X] All active GitHub checks for tests, formatting, and security are passing
- [X] The correct base branch is being used, if not `master`

2022-01-21 22:31 UTC, Widcket commented on internal/auth0/organization.go
> +	// List roles assigned to a member of an organization
```suggestion
	// MemberRoles lists roles assigned to a member of an organization
```

2022-01-21 23:14 UTC, Widcket commented on internal/cli/organizations.go
> +			members, err := cli.getOrgMembers(cmd.Context(), inputs.ID, inputs.Number)
The async operations aren't being done inside a spinner block.

2022-01-21 23:14 UTC, Widcket commented on internal/cli/organizations.go
> +			members, err := cli.getOrgMembers(cmd.Context(), inputs.ID, inputs.Number)
Same as above: the async operations aren't being done inside a spinner block.

2022-01-21 23:15 UTC, Widcket commented on internal/cli/organizations.go
> +				roleList, err := cli.api.Organization.MemberRoles(inputs.ID, userID)
All this logic (that does network calls inside a given command) should be inside a single spinner block.

2022-01-21 23:17 UTC, Widcket commented on internal/cli/organizations.go
> +			members, err := cli.getOrgMembers(cmd.Context(), inputs.OrgID, inputs.Number)
Same as above.

2022-01-21 23:17 UTC, Widcket commented on internal/cli/organizations.go
> +				roleList, err := cli.api.Organization.MemberRoles(inputs.OrgID, userID)
Same as above.

2022-01-21 23:27 UTC, Widcket commented on internal/cli/organizations.go
> +auth0 orgs roles members <org id> <role id>`,
Please, have this command be `auth0 orgs roles members list <org-id> --role-id role`. See `--api-id` in https://auth0.github.io/auth0-cli/auth0_roles_permissions_add.html as an example.
`--role-id` (`-r`) should be a required flag.

2022-01-21 23:32 UTC, Widcket requested changes
Thanks for raising this PR.

Please have the `auth0 orgs roles members <org id> <role id>` command be `auth0 orgs roles members list <org-id> --role-id role` instead, and use spinners for all async operations (one spinner start/stop in the body of a given command).

2022-01-30 23:56 UTC, sergeybykov commented
@Widcket Thanks for the feedback. I think I addressed it all. Could you please take a look.

2022-02-01 02:55 UTC, Widcket requested changes
Running `auth0 orgs roles members list`, it didn't ask to pick the role ID. See https://github.com/auth0/auth0-cli/blob/main/internal/cli/roles_permissions.go#L116 for an example.

2022-02-13 23:14 UTC, sergeybykov commented
@Widcket I added a role picker. Note though that it shows *all* roles within the tenant, not just those used assigned to members of the org. The latter would be cleaner but I think the user experience would be much worse because it takes a long time and many roundtrips to build such a list. We have to do that eventually anyway, but at least that isn't blocking user input.

2022-02-13 23:22 UTC, sergeybykov commented
Added a spinner for the loop that retrieves roles assigned to each member.

2022-02-14 06:16 UTC, Widcket commented
@sergeybykov thanks for making the changes! I'm OOO at the moment, so will re-review when I get back.

2022-02-17 11:14 UTC, sergiughf reviewed
Thanks for your contribution @sergeybykov! I cloned this locally and everything seems to work as per @Widcket's previous feedback. 

I only left a couple of small comments regarding refactoring the code a little bit so it's easier to navigate.

2022-02-17 11:14 UTC, sergiughf commented on internal/cli/organizations.go
> +			})
Would it be possible to abstract this within a func?:) Similar to what we did for `cli.getOrgMembersWithSpinner()` above?

e.g.
```go
memberRoleMap, err := cli.getOrgMemberRolesWithSpinner(...)
```

2022-02-17 11:14 UTC, sergiughf commented on internal/cli/organizations.go
> +			})
Same thing as above, would be great to move this within a func such that we don't need to add the `convert` comment but instead the func name would be self explanatory e.g. `convertOrganizationMemberRolesToRoles()`.

2022-02-17 11:14 UTC, sergiughf commented on internal/cli/organizations.go
> +			sortMembers(roleMembers)
This looks like a candidate as well to be moved within a func so it's easier to navigate the codebase. Wdyt?

2022-02-20 07:18 UTC, sergeybykov commented
@sergiughf I believe I addressed all your comments.

2022-02-21 10:08 UTC, sergiughf approved these changes
Thank you for your contribution @sergeybykov! 🥳  Really good work put into this PR.

2022-02-21 10:11 UTC, merged