DXCDT-314: Add ability to remove roles from a user
auth0/auth0-cli pull request #606
Opened 2023-01-12 19:57 UTC by sergiught

### 🔧 Changes

Add ability to remove roles from a user.

### 📚 References

### 🔬 Testing

### 📝 Checklist

- [ ] All new/changed/fixed functionality is covered by tests (or N/A)
- [x] I have added documentation for all new/changed functionality (or N/A)

2023-01-12 20:30 UTC, Widcket commented on internal/auth0/user.go
> +	// RemoveRoles removes any roles associated to a user.
```suggestion
	// RemoveRoles removes roles from a user.
```

2023-01-13 15:21 UTC, willvedd reviewed
Given that this is a new command, can we add some type of commander test?

2023-01-13 15:53 UTC, willvedd requested changes

2023-01-13 15:53 UTC, willvedd commented on internal/cli/users_roles.go
> +				return cli.api.User.RemoveRoles(inputs.ID, rolesToRemove)
Should check to see if length of `rolesToRemove` is non-zero, otherwise will result in a 400.

2023-01-17 16:31 UTC, willvedd approved these changes
LGTM

2023-01-17 16:44 UTC, merged